[package]
name = "jsonrpc-v1"
version	= "0.2.0"
authors	= ["Andrew Poelstra <apoelstra@wpsoftware.net>", 
           "Jean Pierre De Jesus Dudey Diaz <jeandudey@hotmail.com>",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>"]
license	= "CC0-1.0"
homepage = "https://github.com/exonum/jsonrpc-v1"
repository = "https://github.com/exonum/jsonrpc-v1"
description	= "Rust support for the JSON-RPC 1.0 protocol"
keywords = [ "protocol", "json", "http", "jsonrpc" ]
readme	= "README.md"

[lib]
name = "jsonrpc_v1"
path = "src/lib.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hyper = "0.10.11"
